In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\amuly\OneDrive\Attachments\customer churn project\Telco-Customer-Churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [20]:
df.shape

(7043, 21)

In [21]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [27]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df[df["TotalCharges"].isnull()][["tenure","MonthlyCharges","TotalCharges"]]

Empty DataFrame
Columns: [tenure, MonthlyCharges, TotalCharges]
Index: []

In [7]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [8]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [44]:
churn_rate = round((df["Churn"].value_counts()["Yes"] / len(df)) * 100,2)

In [45]:
print(churn_rate)

26.54

In [46]:
min_tenure = df["tenure"].min()
max_tenure = df["tenure"].max()

In [47]:
print(min_tenure)
print(max_tenure)

0
72

In [48]:
df["tenure"].value_counts()

tenure
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: count, Length: 73, dtype: int64

In [49]:
df.groupby(["tenure","Churn"]).size()

tenure  Churn
0       No        11
1       No       233
        Yes      380
2       No       115
        Yes      123
                ...
70      Yes       11
71      No       164
        Yes        6
72      No       356
        Yes        6
Length: 145, dtype: int64

In [50]:
df["TenureGroup"] = pd.cut(df["tenure"],bins=[0,12,24,48,72],labels=["New Customers","Early Users","Mid-Term Customers","Loyal Customers"])

In [51]:

df[["tenure","TenureGroup"]].head(10)

   tenure         TenureGroup
0       1       New Customers
1      34  Mid-Term Customers
2       2       New Customers
3      45  Mid-Term Customers
4       2       New Customers
5       8       New Customers
6      22         Early Users
7      10       New Customers
8      28  Mid-Term Customers
9      62     Loyal Customers

In [55]:
df.groupby(["TenureGroup","Churn"]).size()

C:\Users\amuly\AppData\Local\Temp\ipykernel_48648\4270476709.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["TenureGroup","Churn"]).size()

TenureGroup         Churn
New Customers       No       1138
                    Yes      1037
Early Users         No        730
                    Yes       294
Mid-Term Customers  No       1269
                    Yes       325
Loyal Customers     No       2026
                    Yes       213
dtype: int64

In [56]:
#Customers in the first 12 months show the highest churn risk, indicating potential onboarding or early experience issues.

In [79]:
tenure_churn = df.groupby(["TenureGroup","Churn"]).size().unstack()

C:\Users\amuly\AppData\Local\Temp\ipykernel_48648\2197952470.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tenure_churn = df.groupby(["TenureGroup","Churn"]).size().unstack()

In [80]:
tenure_churn

Churn                 No   Yes
TenureGroup
New Customers       1138  1037
Early Users          730   294
Mid-Term Customers  1269   325
Loyal Customers     2026   213

In [86]:
tenure_churn["ChurnRate"] = round((tenure_churn["Yes"] / (tenure_churn["Yes"] + tenure_churn["No"])) * 100, 2)
tenure_churn

Churn                 No   Yes  ChurnRate
TenureGroup
New Customers       1138  1037      47.68
Early Users          730   294      28.71
Mid-Term Customers  1269   325      20.39
Loyal Customers     2026   213       9.51

In [87]:
tenure_churn

Churn                 No   Yes  ChurnRate
TenureGroup
New Customers       1138  1037      47.68
Early Users          730   294      28.71
Mid-Term Customers  1269   325      20.39
Loyal Customers     2026   213       9.51

In [4]:
contract_churn = df.groupby(["Contract","Churn"]).size().unstack()
contract_churn

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [5]:
contract_churn["ChurnRate"] = round(
    (contract_churn["Yes"] / (contract_churn["Yes"] + contract_churn["No"])) * 100, 2
)

contract_churn

Churn             No   Yes  ChurnRate
Contract
Month-to-month  2220  1655      42.71
One year        1307   166      11.27
Two year        1647    48       2.83

In [9]:
#Create a table comparing that column with churn

In [10]:
df.groupby(["InternetService","Churn"]).size().unstack()

Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

In [12]:
internet_churn = df.groupby(["InternetService","Churn"]).size().unstack()
internet_churn

Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

In [13]:
internet_churn["ChurnRate"] = round(
    (internet_churn["Yes"] / (internet_churn["Yes"] + internet_churn["No"])) * 100, 2
)

internet_churn

Churn              No   Yes  ChurnRate
InternetService
DSL              1962   459      18.96
Fiber optic      1799  1297      41.89
No               1413   113       7.40

In [5]:
security_churn = df.groupby(["OnlineSecurity","Churn"]).size().unstack()
security_churn

Churn                  No   Yes
OnlineSecurity
No                   2037  1461
No internet service  1413   113
Yes                  1724   295

In [6]:
security_churn["ChurnRate"] = round(
    (security_churn["Yes"] / (security_churn["Yes"] + security_churn["No"])) * 100, 2
)

security_churn

Churn                  No   Yes  ChurnRate
OnlineSecurity
No                   2037  1461      41.77
No internet service  1413   113       7.40
Yes                  1724   295      14.61

In [4]:
tech_churn = df.groupby(["TechSupport","Churn"]).size().unstack()
tech_churn

Churn                  No   Yes
TechSupport
No                   2027  1446
No internet service  1413   113
Yes                  1734   310

In [5]:
tech_churn["ChurnRate"] = round(
    (tech_churn["Yes"] / (tech_churn["Yes"] + tech_churn["No"])) * 100, 2
)

tech_churn

Churn                  No   Yes  ChurnRate
TechSupport
No                   2027  1446      41.64
No internet service  1413   113       7.40
Yes                  1734   310      15.17

In [3]:
pd.crosstab(df["PaymentMethod"], df["Churn"])

Churn                        No   Yes
PaymentMethod
Bank transfer (automatic)  1286   258
Credit card (automatic)    1290   232
Electronic check           1294  1071
Mailed check               1304   308

In [4]:
payment_churn = pd.crosstab(df["PaymentMethod"], df["Churn"])

payment_churn["ChurnRate"] = round(
    (payment_churn["Yes"] / (payment_churn["Yes"] + payment_churn["No"])) * 100, 2
)

payment_churn

Churn                        No   Yes  ChurnRate
PaymentMethod
Bank transfer (automatic)  1286   258      16.71
Credit card (automatic)    1290   232      15.24
Electronic check           1294  1071      45.29
Mailed check               1304   308      19.11